jenkins:
  controller:
    image:
      tag: "2.565"

    numExecutors: 3

    csrf:
      defaultCrumbIssuer:
        enabled: false
    ingress:
      enabled: true
      hostName: jenkins.local
      ingressClassName: traefik
      
    installPlugins:
      - kubernetes:4203.v1dd44f5b_1cf9
      - workflow-aggregator:596.v8c21c963d92d
      - git
      - configuration-as-code:2053.vb_0da_47381a_25

    additionalPlugins:
      # --- Pipeline ---
      - workflow-multibranch
      - branch-api

      # --- Git / GitHub ---
      - github
      - github-branch-source

      # --- Build ---
      - gradle

      # --- Credentials ---
      - credentials-binding
      - plain-credentials
      - ssh-credentials
      - ssh-agent

      # --- Test Reporting ---
      - junit

      # --- Utility ---
      - timestamper
      - ansicolor
      - ws-cleanup
      - build-timeout